### ISSUE TITLE
Generator does not respect origin given in the map.yaml

### ISSUE THREAD

**Issue by kurshakuz** [fverdoja/ros_maps_to_pedsim#1]
Hi! You have done a great job!

I have been trying to use your package and found a minor error that could be easily fixed. The problem is that the script does not take the origin given in the map.yaml into account. The origin happens to be non-zero sometimes when you build map with gmapping and the same was in my case. The map in gazebo was not aligning with the map in pedsim. So I just added the following lines to the `scenario_from_map` function. 

```
 origin = map_metadata['origin']
 ...
                world_x = origin[0] + y * resolution
                world_y = origin[1] - (x - sz[0]) * resolution
```

Hope that it helps anyone too.

**Comment by fverdoja** [comment]
Hi,
thanks for noticing this. I used origin [0, 0, 0] because that seemed to work better with `pedsim_ros`. I have however now added a parameter to the launch file called `use_map_origin` that if set to true does what you suggested.

Thanks for your help!
